"""Problemas sociais canônicos (base: taxonomia da seção 3 da V3) e o mapa
dos termos livres dos registros para eles.

- origin "V3-taxonomia": subeixo exatamente como na seção 3 (só desambiguado no nome)
- origin "curadoria": acrescentado na conversão — PRECISA de aprovação do Eduardo
"""

MACROEIXOS = [
    # slug, nome (como na pesquisa), origin
    ("saude", "Saúde", "V3-taxonomia"),
    ("educacao", "Educação", "V3-taxonomia"),
    ("infancia-adolescencia", "Infância e adolescência", "V3-taxonomia"),
    ("juventude", "Juventude", "V3-taxonomia"),
    ("tecnologia-sociedade", "Tecnologia e sociedade", "V3-taxonomia"),
    ("trabalho-cuidado", "Trabalho e cuidado", "V3-taxonomia"),
    ("pcd-neurodiversidade", "PcD e neurodiversidade", "V3-taxonomia"),
    ("invisibilidade-social", "Invisibilidade social", "V3-taxonomia"),
    ("raca-genero", "Raça e gênero", "V3-taxonomia"),
    ("cidades-clima", "Cidades e clima", "V3-taxonomia"),
    ("envelhecimento", "Envelhecimento", "V3-taxonomia"),
    ("violencia-seguranca", "Violência e segurança", "V3-taxonomia"),
    # A V3 cria o "bloco" indígena (seções 15 e 19), mas a tabela da taxonomia é a da V2
    ("povos-indigenas", "Povos indígenas e comunidades tradicionais", "curadoria"),
]

PROBLEMAS = [
    # slug, nome, macroeixo, origin
    ("desigualdade-saude", "Desigualdade em saúde", "saude", "V3-taxonomia"),
    ("sus-acesso-saude", "SUS e acesso à saúde", "saude", "V3-taxonomia"),
    ("saude-mental", "Saúde mental", "saude", "V3-taxonomia"),
    ("prevencao-saude", "Prevenção em saúde", "saude", "V3-taxonomia"),
    ("alfabetizacao", "Alfabetização e letramento", "educacao", "V3-taxonomia"),
    ("eja", "EJA e educação de adultos", "educacao", "V3-taxonomia"),
    ("evasao-escolar", "Evasão e permanência escolar", "educacao", "V3-taxonomia"),
    ("inclusao-educacional", "Inclusão e desigualdade educacional", "educacao", "V3-taxonomia"),
    ("neurodiversidade-escola", "Neurodiversidade na escola", "educacao", "V3-taxonomia"),
    ("protecao-integral", "Proteção integral da infância", "infancia-adolescencia", "V3-taxonomia"),
    ("infancia-digital", "Infância no ambiente digital", "infancia-adolescencia", "V3-taxonomia"),
    ("trabalho-infantil", "Trabalho infantil", "infancia-adolescencia", "V3-taxonomia"),
    ("violencia-juventude", "Violência contra a juventude", "juventude", "V3-taxonomia"),
    ("trabalho-juventude", "Juventude e trabalho", "juventude", "V3-taxonomia"),
    ("participacao-juventude", "Participação juvenil", "juventude", "V3-taxonomia"),
    ("perspectiva-futuro", "Perspectiva de futuro", "juventude", "V3-taxonomia"),
    ("plataformas-digitais", "Plataformas digitais", "tecnologia-sociedade", "V3-taxonomia"),
    ("dados-privacidade", "Dados e privacidade", "tecnologia-sociedade", "V3-taxonomia"),
    ("algoritmos", "Algoritmos e IA", "tecnologia-sociedade", "V3-taxonomia"),
    ("inclusao-digital", "Inclusão digital", "tecnologia-sociedade", "V3-taxonomia"),
    ("precarizacao-trabalho", "Precarização do trabalho", "trabalho-cuidado", "V3-taxonomia"),
    ("plataformizacao-trabalho", "Plataformização do trabalho", "trabalho-cuidado", "V3-taxonomia"),
    ("trabalho-domestico", "Trabalho doméstico", "trabalho-cuidado", "V3-taxonomia"),
    ("trabalho-cuidado", "Trabalho de cuidado", "trabalho-cuidado", "V3-taxonomia"),
    ("acessibilidade", "Acessibilidade", "pcd-neurodiversidade", "V3-taxonomia"),
    ("inclusao-escolar-pcd", "Inclusão escolar de PcD", "pcd-neurodiversidade", "V3-taxonomia"),
    ("trabalho-pcd", "PcD e trabalho", "pcd-neurodiversidade", "V3-taxonomia"),
    ("populacao-rua", "População em situação de rua", "invisibilidade-social", "V3-taxonomia"),
    ("trabalhos-invisibilizados", "Trabalhos invisibilizados", "invisibilidade-social", "V3-taxonomia"),
    ("pobreza", "Pobreza", "invisibilidade-social", "V3-taxonomia"),
    ("racismo", "Racismo", "raca-genero", "V3-taxonomia"),
    ("sexismo", "Sexismo e desigualdade de gênero", "raca-genero", "V3-taxonomia"),
    ("identidade", "Identidade e representação", "raca-genero", "V3-taxonomia"),
    ("discriminacao", "Discriminação", "raca-genero", "V3-taxonomia"),
    ("moradia", "Moradia", "cidades-clima", "V3-taxonomia"),
    ("segregacao-urbana", "Segregação urbana e direito à cidade", "cidades-clima", "V3-taxonomia"),
    ("seca", "Seca e deslocamento", "cidades-clima", "V3-taxonomia"),
    ("calor-extremo", "Calor extremo e eventos climáticos", "cidades-clima", "V3-taxonomia"),
    ("justica-climatica", "Justiça climática e ambiental", "cidades-clima", "V3-taxonomia"),
    ("meio-ambiente", "Meio ambiente, resíduos e saneamento", "cidades-clima", "curadoria"),
    ("etarismo", "Etarismo", "envelhecimento", "V3-taxonomia"),
    ("cuidado-pessoa-idosa", "Cuidado da pessoa idosa", "envelhecimento", "V3-taxonomia"),
    ("autonomia-pessoa-idosa", "Autonomia da pessoa idosa", "envelhecimento", "V3-taxonomia"),
    ("inclusao-pessoa-idosa", "Inclusão da pessoa idosa", "envelhecimento", "V3-taxonomia"),
    ("violencia-urbana", "Violência urbana", "violencia-seguranca", "V3-taxonomia"),
    ("violencia-racial", "Violência racial", "violencia-seguranca", "V3-taxonomia"),
    ("violencia-institucional", "Violência institucional", "violencia-seguranca", "V3-taxonomia"),
    ("violencia-escolar", "Violência escolar", "violencia-seguranca", "V3-taxonomia"),
    ("territorio-indigena", "Território indígena", "povos-indigenas", "curadoria"),
    ("cultura-memoria-indigena", "Cultura e memória indígena", "povos-indigenas", "curadoria"),
    ("direitos-indigenas", "Direitos indígenas", "povos-indigenas", "curadoria"),
    ("saude-indigena", "Saúde indígena", "povos-indigenas", "curadoria"),
]

# termo livre (minúsculo) -> problemas canônicos. [] = fica só como tag de busca.
MAPA = {
    "acessibilidade": ["acessibilidade"], "acesso": [], "acesso ao ensino superior": ["inclusao-educacional"],
    "acesso à justiça": ["direitos-indigenas"], "acesso à saúde": ["sus-acesso-saude"], "adaptação": ["justica-climatica"],
    "aee": ["inclusao-escolar-pcd"], "alfabetização": ["alfabetizacao"], "algoritmos": ["algoritmos"],
    "alimentação": ["prevencao-saude"], "amazônia": ["justica-climatica"], "analfabetismo": ["alfabetizacao", "eja"],
    "analfabetismo funcional": ["alfabetizacao"], "apagamento histórico": ["identidade"],
    "assimetria informacional": ["dados-privacidade"], "autodeterminação": ["direitos-indigenas"],
    "automação": ["precarizacao-trabalho"], "autonomia": ["autonomia-pessoa-idosa"],
    "avaliação biopsicossocial": ["acessibilidade"], "ações afirmativas": ["racismo", "inclusao-educacional"],
    "barreiras de acesso": ["sus-acesso-saude"], "barreiras escolares": ["inclusao-escolar-pcd"], "bpc": ["acessibilidade"],
    "calor extremo": ["calor-extremo"], "capacitismo": ["acessibilidade", "discriminacao"], "cidadania": [],
    "cidade": ["segregacao-urbana"], "cidades amigáveis": ["inclusao-pessoa-idosa"], "clima": ["justica-climatica"],
    "colonialismo": ["territorio-indigena"], "consumo": ["infancia-digital"], "cuidado": ["trabalho-cuidado"],
    "cuidado em liberdade": ["saude-mental"], "cultura": [], "cultura afro-brasileira": ["identidade", "racismo"],
    "currículo": ["inclusao-educacional"], "dados": ["dados-privacidade"], "dcnt": ["prevencao-saude"],
    "desenvolvimento": [], "desigualdade": [], "desigualdade de acesso": [], "desigualdade de classe": ["pobreza"],
    "desigualdade de gênero": ["sexismo"], "desigualdade educacional": ["inclusao-educacional"],
    "desigualdade em saúde": ["desigualdade-saude"], "desigualdade no acesso à saúde": ["desigualdade-saude", "sus-acesso-saude"],
    "desigualdade regional": [], "desigualdade territorial": ["segregacao-urbana"], "desigualdade urbana": ["segregacao-urbana"],
    "desinformação": ["algoritmos"], "determinantes sociais": ["desigualdade-saude"], "dignidade": [],
    "direito à cidade": ["segregacao-urbana"], "direitos coletivos": ["direitos-indigenas"],
    "direitos indígenas": ["direitos-indigenas"], "discriminação": ["discriminacao"],
    "discriminação algorítmica": ["algoritmos", "discriminacao"], "documentação": ["populacao-rua"],
    "economia da atenção": ["plataformas-digitais", "infancia-digital"], "educação": [],
    "educação antirracista": ["racismo", "inclusao-educacional"], "educação de adultos": ["eja"],
    "educação do campo": ["inclusao-educacional"], "educação inclusiva": ["inclusao-escolar-pcd", "inclusao-educacional"],
    "eja": ["eja"], "enchentes": ["calor-extremo", "justica-climatica"], "ensino autoritário": ["inclusao-educacional"],
    "entregadores": ["plataformizacao-trabalho"], "envelhecimento": ["inclusao-pessoa-idosa"], "equidade": [],
    "escravidão": ["racismo"], "especulação imobiliária": ["moradia", "segregacao-urbana"], "estigma": ["discriminacao"],
    "etarismo": ["etarismo"], "evasão": ["evasao-escolar"], "eventos extremos": ["calor-extremo"], "exclusão": [],
    "exploração online": ["infancia-digital", "protecao-integral"], "floresta": ["territorio-indigena", "justica-climatica"],
    "formação cidadã": ["participacao-juventude"], "formação docente": ["inclusao-educacional"],
    "garimpo": ["territorio-indigena"], "gestão algorítmica": ["plataformizacao-trabalho", "algoritmos"],
    "globalização": [], "gênero": ["sexismo"], "ia": ["algoritmos"], "identidade": ["identidade"],
    "identidade negra": ["identidade", "racismo"], "inclusão": ["inclusao-educacional"],
    "influenciadores mirins": ["infancia-digital", "trabalho-infantil"], "informalidade": ["precarizacao-trabalho"],
    "infância": ["protecao-integral"], "institucionalização": ["saude-mental", "violencia-institucional"],
    "invisibilidade": ["trabalhos-invisibilizados"], "invisibilidade social": ["trabalhos-invisibilizados"],
    "jornada": ["precarizacao-trabalho"], "justiça ambiental": ["justica-climatica"], "justiça climática": ["justica-climatica"],
    "juventude": [], "letramento": ["alfabetizacao"], "liberdade": [], "maternidade": ["trabalho-cuidado", "sexismo"],
    "meio ambiente": ["meio-ambiente"], "memória": [], "migração": ["seca"], "moradia": ["moradia"], "ocupações": ["moradia"],
    "participação": ["participacao-juventude"], "participação política": ["participacao-juventude"], "patrimônio": ["identidade"],
    "pcd": ["acessibilidade"], "pertencimento": ["identidade"], "plataformas": ["plataformas-digitais"],
    "pobreza": ["pobreza"], "policiamento": ["violencia-institucional"], "políticas de deficiência": ["acessibilidade"],
    "políticas de saúde": ["sus-acesso-saude"], "políticas de saúde mental": ["saude-mental"], "políticas públicas": [],
    "políticas sociais": [], "população em situação de rua": ["populacao-rua"], "povos tradicionais": ["direitos-indigenas"],
    "precarização": ["precarizacao-trabalho"], "prevenção": ["prevencao-saude"], "previdência": ["precarizacao-trabalho"],
    "prisões": ["violencia-institucional"], "privacidade": ["dados-privacidade"], "proteção de dados": ["dados-privacidade"],
    "proteção do trabalho": ["precarizacao-trabalho"], "publicidade infantil": ["infancia-digital"],
    "racismo": ["racismo"], "racismo escolar": ["racismo", "violencia-escolar"], "raps": ["saude-mental"], "rastreamento": ["dados-privacidade"],
    "raça": ["racismo"], "reconhecimento": ["trabalhos-invisibilizados"], "resíduos": ["meio-ambiente"], "rua": ["populacao-rua"],
    "saneamento": ["meio-ambiente"], "saúde": [], "saúde da pessoa idosa": ["cuidado-pessoa-idosa"],
    "saúde da população negra": ["desigualdade-saude", "racismo"], "saúde indígena": ["saude-indigena"],
    "saúde mental juvenil": ["saude-mental"], "saúde preventiva": ["prevencao-saude"], "segurança": ["violencia-urbana"],
    "seletividade institucional": ["violencia-institucional"], "sem-teto": ["moradia"], "soberania de dados": ["dados-privacidade"],
    "sucesso/fracasso escolar": ["evasao-escolar", "inclusao-educacional"], "sus": ["sus-acesso-saude"],
    "tecnologia": [], "terceirização": ["precarizacao-trabalho"], "território": [], "trabalhadores invisibilizados": ["trabalhos-invisibilizados"],
    "trabalhadores subalternizados": ["trabalhos-invisibilizados"], "trabalho": [], "trabalho de cuidado": ["trabalho-cuidado"],
    "trabalho doméstico": ["trabalho-domestico"], "trabalho infantil": ["trabalho-infantil"],
    "trabalho por aplicativos": ["plataformizacao-trabalho"], "transformações do trabalho": ["precarizacao-trabalho"],
    "transporte": ["segregacao-urbana"], "tratamento desumanizado": ["saude-mental", "violencia-institucional"],
    "uberização": ["plataformizacao-trabalho"], "urbanização": ["segregacao-urbana"], "vigilância digital": ["dados-privacidade"],
    "violência": [], "violência racial": ["violencia-racial"], "violência simbólica": ["inclusao-educacional"],
    "violência urbana": ["violencia-urbana"], "visibilidade": ["identidade"],
    "vulnerabilidade territorial": ["justica-climatica"], "youtube": ["infancia-digital"],
}

# Termos genéricos ("cultura", "território", "memória", "trabalho"…) não viram problema
# sozinhos; quando o registro precisa deles, a decisão vem aqui, por registro.
POR_REGISTRO = {
    "REP-055": ["territorio-indigena", "cultura-memoria-indigena"],
    "REP-056": ["territorio-indigena", "direitos-indigenas"],
    "REP-057": ["territorio-indigena", "cultura-memoria-indigena"],
    "REP-058": ["cultura-memoria-indigena"],
    "CF-008": ["identidade"],
    "CF-011": ["territorio-indigena", "direitos-indigenas", "cultura-memoria-indigena"],
}
